/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "RangingBacktestBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "RangingBotApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "RangingBotRuns": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RangingKlineCache": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "RangingRealtime": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "RangingRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}