import type {
  StrategyConfigJsonSchema,
  StrategyConfigUiField,
} from "@repo/trading-engine";
import { z } from "zod";
import type { IndicatorBotConfig } from "./types";

export const defaultIndicatorBotConfig: IndicatorBotConfig = {
  trend: {
    fastEmaLength: 21,
    slowEmaLength: 55,
    higherTimeframeEmaLength: 34,
    slopeLookbackBars: 3,
    minEmaSeparationPct: 0.003,
    maxPriceDistanceFromFastEmaPct: 0.008,
  },
  momentum: {
    rsiLength: 14,
    longThreshold: 55,
    longCeiling: 68,
    shortThreshold: 45,
    shortFloor: 32,
  },
  volatility: {
    atrLength: 14,
    stopAtrMultiple: 1.8,
  },
  volume: {
    requireExpansion: false,
    volumeSmaLength: 20,
    minVolumeRatio: 1.1,
  },
  execution: {
    requirePrimaryTrendConfirmation: true,
    requireSecondaryTrendConfirmation: false,
    closeOnOppositeSignal: true,
  },
  risk: {
    riskPctPerTrade: 0.01,
    maxNotionalPctEquity: 1,
    tp1RewardMultiple: 1.5,
    tp2RewardMultiple: 3,
    tp1SizePct: 0.5,
    tp2SizePct: 0.5,
    moveStopToBreakevenOnTp1: true,
    cooldownBars: 2,
  },
};

export const indicatorBotConfigSchema = z.object({
  trend: z.object({
    fastEmaLength: z.number().int().min(2).max(200).default(21),
    slowEmaLength: z.number().int().min(5).max(400).default(55),
    higherTimeframeEmaLength: z.number().int().min(5).max(400).default(34),
    slopeLookbackBars: z.number().int().min(1).max(20).default(3),
    minEmaSeparationPct: z.number().min(0).max(0.05).default(0.003),
    maxPriceDistanceFromFastEmaPct: z
      .number()
      .min(0.001)
      .max(0.05)
      .default(0.008),
  }),
  momentum: z.object({
    rsiLength: z.number().int().min(2).max(100).default(14),
    longThreshold: z.number().min(1).max(99).default(55),
    longCeiling: z.number().min(1).max(99).default(68),
    shortThreshold: z.number().min(1).max(99).default(45),
    shortFloor: z.number().min(1).max(99).default(32),
  }),
  volatility: z.object({
    atrLength: z.number().int().min(2).max(100).default(14),
    stopAtrMultiple: z.number().min(0.5).max(10).default(1.8),
  }),
  volume: z.object({
    requireExpansion: z.boolean().default(false),
    volumeSmaLength: z.number().int().min(2).max(100).default(20),
    minVolumeRatio: z.number().min(0.5).max(5).default(1.1),
  }),
  execution: z.object({
    requirePrimaryTrendConfirmation: z.boolean().default(true),
    requireSecondaryTrendConfirmation: z.boolean().default(false),
    closeOnOppositeSignal: z.boolean().default(true),
  }),
  risk: z.object({
    riskPctPerTrade: z.number().min(0.001).max(0.05).default(0.01),
    maxNotionalPctEquity: z.number().min(0.05).max(10).default(1),
    tp1RewardMultiple: z.number().min(0.5).max(10).default(1.5),
    tp2RewardMultiple: z.number().min(1).max(20).default(3),
    tp1SizePct: z.number().min(0.05).max(1).default(0.5),
    tp2SizePct: z.number().min(0.05).max(1).default(0.5),
    moveStopToBreakevenOnTp1: z.boolean().default(true),
    cooldownBars: z.number().int().min(0).max(50).default(2),
  }),
});

export const indicatorBotConfigJsonSchema = z.toJSONSchema(
  indicatorBotConfigSchema,
) as StrategyConfigJsonSchema;

export const indicatorBotConfigUi: StrategyConfigUiField[] = [
  {
    path: "trend.fastEmaLength",
    widget: "number",
    label: "Fast EMA",
    description: "Fast trend average on the execution timeframe.",
    section: "Trend",
    suffix: "bars",
    order: 10,
  },
  {
    path: "trend.slowEmaLength",
    widget: "number",
    label: "Slow EMA",
    description: "Slow trend average on the execution timeframe.",
    section: "Trend",
    suffix: "bars",
    order: 20,
  },
  {
    path: "trend.higherTimeframeEmaLength",
    widget: "number",
    label: "Higher timeframe EMA",
    description: "EMA used to classify the higher timeframe regime.",
    section: "Trend",
    suffix: "bars",
    order: 30,
  },
  {
    path: "trend.slopeLookbackBars",
    widget: "number",
    label: "Slope lookback",
    description: "Bars used to confirm EMA slope direction.",
    section: "Trend",
    suffix: "bars",
    order: 40,
  },
  {
    path: "trend.minEmaSeparationPct",
    widget: "number",
    label: "Minimum EMA separation %",
    description: "Minimum trend spread required between fast and slow EMA.",
    section: "Trend",
    valueFormat: "fraction-percent",
    suffix: "%",
    decimals: 2,
    order: 50,
  },
  {
    path: "trend.maxPriceDistanceFromFastEmaPct",
    widget: "number",
    label: "Max distance from fast EMA %",
    description: "Prevents chasing entries too far from the pullback area.",
    section: "Trend",
    valueFormat: "fraction-percent",
    suffix: "%",
    decimals: 2,
    order: 60,
  },
  {
    path: "momentum.rsiLength",
    widget: "number",
    label: "RSI length",
    description: "Momentum filter length on the execution timeframe.",
    section: "Momentum",
    suffix: "bars",
    order: 70,
  },
  {
    path: "momentum.longThreshold",
    widget: "number",
    label: "Long RSI floor",
    description: "Minimum RSI required to validate long momentum.",
    section: "Momentum",
    order: 80,
  },
  {
    path: "momentum.longCeiling",
    widget: "number",
    label: "Long RSI ceiling",
    description: "Maximum RSI allowed for long entries to avoid late chasing.",
    section: "Momentum",
    order: 90,
  },
  {
    path: "momentum.shortThreshold",
    widget: "number",
    label: "Short RSI ceiling",
    description: "Maximum RSI allowed to validate short momentum.",
    section: "Momentum",
    order: 100,
  },
  {
    path: "momentum.shortFloor",
    widget: "number",
    label: "Short RSI floor",
    description: "Minimum RSI floor for shorts to avoid exhausted moves.",
    section: "Momentum",
    order: 110,
  },
  {
    path: "volume.requireExpansion",
    widget: "boolean",
    label: "Require volume expansion",
    description: "Only trigger when current volume confirms the setup.",
    section: "Volume",
    order: 120,
  },
  {
    path: "volume.minVolumeRatio",
    widget: "number",
    label: "Minimum volume ratio",
    description: "Current volume divided by volume SMA must exceed this ratio.",
    section: "Volume",
    order: 130,
  },
  {
    path: "execution.requirePrimaryTrendConfirmation",
    widget: "boolean",
    label: "Require primary trend confirmation",
    description: "Align entries with the primary higher timeframe trend.",
    section: "Execution",
    order: 140,
  },
  {
    path: "execution.requireSecondaryTrendConfirmation",
    widget: "boolean",
    label: "Require secondary trend confirmation",
    description: "Align entries with the secondary higher timeframe trend.",
    section: "Execution",
    order: 150,
  },
  {
    path: "execution.closeOnOppositeSignal",
    widget: "boolean",
    label: "Close on opposite signal",
    description: "Exit the runner if a confirmed opposite setup appears.",
    section: "Execution",
    order: 160,
  },
  {
    path: "risk.riskPctPerTrade",
    widget: "number",
    label: "Risk % per trade",
    description: "Fraction of equity risked between entry and stop.",
    section: "Risk",
    valueFormat: "fraction-percent",
    suffix: "%",
    decimals: 2,
    order: 170,
  },
  {
    path: "risk.maxNotionalPctEquity",
    widget: "number",
    label: "Max notional x equity",
    description: "Caps gross notional used by each position.",
    section: "Risk",
    order: 180,
  },
  {
    path: "volatility.stopAtrMultiple",
    widget: "number",
    label: "ATR stop multiple",
    description: "Stop distance expressed in ATR.",
    section: "Risk",
    order: 190,
  },
  {
    path: "risk.tp1RewardMultiple",
    widget: "number",
    label: "TP1 reward multiple",
    description: "Risk multiple for the first target.",
    section: "Risk",
    order: 200,
  },
  {
    path: "risk.tp2RewardMultiple",
    widget: "number",
    label: "TP2 reward multiple",
    description: "Risk multiple for the second target.",
    section: "Risk",
    order: 210,
  },
  {
    path: "risk.tp1SizePct",
    widget: "number",
    label: "TP1 size %",
    description: "Portion of the position reduced at TP1.",
    section: "Risk",
    valueFormat: "fraction-percent",
    suffix: "%",
    decimals: 0,
    order: 220,
  },
  {
    path: "risk.tp2SizePct",
    widget: "number",
    label: "TP2 size %",
    description: "Portion of the position reduced at TP2.",
    section: "Risk",
    valueFormat: "fraction-percent",
    suffix: "%",
    decimals: 0,
    order: 230,
  },
  {
    path: "risk.moveStopToBreakevenOnTp1",
    widget: "boolean",
    label: "Move stop to breakeven at TP1",
    description: "Protect runner risk once the first target is reached.",
    section: "Risk",
    order: 240,
  },
  {
    path: "risk.cooldownBars",
    widget: "number",
    label: "Cooldown bars",
    description: "Bars to wait after a full close before re-entry.",
    section: "Risk",
    suffix: "bars",
    order: 250,
  },
];

export function createIndicatorBotConfig(
  overrides?: Partial<IndicatorBotConfig>,
): IndicatorBotConfig {
  return indicatorBotConfigSchema.parse({
    ...defaultIndicatorBotConfig,
    ...overrides,
    trend: {
      ...defaultIndicatorBotConfig.trend,
      ...overrides?.trend,
    },
    momentum: {
      ...defaultIndicatorBotConfig.momentum,
      ...overrides?.momentum,
    },
    volatility: {
      ...defaultIndicatorBotConfig.volatility,
      ...overrides?.volatility,
    },
    volume: {
      ...defaultIndicatorBotConfig.volume,
      ...overrides?.volume,
    },
    execution: {
      ...defaultIndicatorBotConfig.execution,
      ...overrides?.execution,
    },
    risk: {
      ...defaultIndicatorBotConfig.risk,
      ...overrides?.risk,
    },
  });
}
